from typing import List, Optional, Literal
from pydantic import BaseModel, Field


class JobDescriptionInput(BaseModel):
    job_title: Optional[str] = Field(default=None, description="Job title if known")
    company_name: Optional[str] = Field(default=None, description="Hiring company if known")
    raw_text: str = Field(min_length=15, description="Full job description text")


class JobRequirementsDecomposed(BaseModel):
    inferred_title: str = Field(description="Role title extracted from JD")
    inferred_industry: str = Field(description="Industry or field (e.g. Healthcare, Marketing, Software, Logistics, Finance)")
    experience_level: str = Field(description="Target seniority (Entry, Mid, Senior, Lead, Executive)")
    must_have_skills: List[str] = Field(default_factory=list, description="Core mandatory qualifications")
    nice_to_have_skills: List[str] = Field(default_factory=list, description="Preferred or bonus qualifications")
    key_responsibilities: List[str] = Field(default_factory=list, description="Primary duties expected in role")
    cultural_and_soft_skills: List[str] = Field(default_factory=list, description="Collaboration, communication, or leadership expectations")


class MatchDimensionScores(BaseModel):
    overall_score: int = Field(ge=0, le=100, description="Weighted composite match score from 0-100")
    skills_match_score: int = Field(ge=0, le=100, description="Keyword & capability overlap score")
    experience_match_score: int = Field(ge=0, le=100, description="Seniority, tenure, and scope match score")
    domain_depth_score: int = Field(ge=0, le=100, description="Domain specific knowledge and terminology depth")
    education_cert_score: int = Field(ge=0, le=100, description="Degrees, licenses, and certification compliance")
    verdict: str = Field(description="Quick verdict (e.g. 'Strong Contender', 'High Potential / Minor Gaps', 'Needs Targeted Positioning')")


class SkillMatchItem(BaseModel):
    skill_name: str
    status: Literal["matched", "partial", "missing"] = "matched"
    importance: Literal["critical", "important", "bonus"] = "critical"
    evidence_or_notes: str = Field(description="Citation or explanation of presence/absence in resume")


class SkillGapAnalysis(BaseModel):
    matched_skills: List[SkillMatchItem] = Field(default_factory=list)
    missing_critical_skills: List[SkillMatchItem] = Field(default_factory=list)
    missing_secondary_skills: List[SkillMatchItem] = Field(default_factory=list)
    bridge_recommendations: List[str] = Field(default_factory=list, description="Actionable advice to bridge missing gaps")


class ATSCheckItem(BaseModel):
    category: str = Field(description="e.g., 'Action Verbs', 'Quantified Metrics', 'Contact Info', 'Keyword Optimization'")
    status: Literal["pass", "warning", "fail"] = "pass"
    title: str = Field(description="Check title")
    detail: str = Field(description="Specific finding in resume")
    fix_action: str = Field(description="Exact recommendation to pass ATS filters")


class ATSReport(BaseModel):
    ats_score: int = Field(ge=0, le=100, description="ATS Readability & Parseability score 0-100")
    overall_readability: str = Field(description="Assessment of machine and human readability")
    checks: List[ATSCheckItem] = Field(default_factory=list)
    top_ats_improvements: List[str] = Field(default_factory=list)


class RewriteSuggestion(BaseModel):
    section: str = Field(description="Target section (e.g. 'Experience: Senior Clinician at Mercy Hospital')")
    original_bullet: str = Field(description="Original bullet from resume")
    rewritten_bullet: str = Field(description="Action-oriented, quantified rewrite")
    reasoning: str = Field(description="Why this rewrite increases recruiter interest and JD alignment")
    framework_used: str = Field(default="Google XYZ / STAR Framework (Accomplished [X] as measured by [Y] by doing [Z])")
    impact_level: Literal["High", "Medium"] = "High"


class ResumeAnalysisResult(BaseModel):
    """Full career intelligence result generated by LangGraph pipeline."""
    session_id: Optional[str] = None
    match_scores: MatchDimensionScores
    job_breakdown: JobRequirementsDecomposed
    skill_gaps: SkillGapAnalysis
    ats_report: ATSReport
    rewrite_suggestions: List[RewriteSuggestion] = Field(default_factory=list)
    executive_summary: str = Field(description="Holistic recruiter briefing on candidate suitability")
    strengths: List[str] = Field(default_factory=list, description="Top 3-5 standout strengths for this role")
    weaknesses: List[str] = Field(default_factory=list, description="Key vulnerability or gap areas to address")
    interview_prep_questions: List[str] = Field(default_factory=list, description="Tailored mock interview questions based on candidate gaps")
    pipeline_execution_logs: List[dict] = Field(default_factory=list, description="Execution traces and timing per LangGraph node")
